In [1]:
#Прудкий Ігор Станіславович
#18 Варіант
import numpy as np


In [3]:
#1.	Створіть одновимірний масив (вектор) з числами, які є кубами натуральних чисел, починаючи з 1, та виведіть його значення.
import numpy as np

a = np.arange(1, 11) ** 3

# Виведення значень вектора
print(a)

[   1    8   27   64  125  216  343  512  729 1000]


In [4]:
#2.	Створіть двовимірний масив (матрицю) розміром 3x3, 
#заповніть його значеннями факторіалів кожного числа плюс його попереднього числа, починаючи з 1, та виведіть його значення.

import math
matrix = np.zeros((3, 3), dtype=int)
for i in range(3):
    for j in range(3):
        current_number = i * 3 + j + 1
        factorial = np.math.factorial(current_number)
        previous_number = current_number - 1 if current_number > 1 else 0
        matrix[i, j] = factorial + previous_number

print(matrix)


[[     1      3      8]
 [    27    124    725]
 [  5046  40327 362888]]


In [6]:
#3.Створіть масив розміром 9x9, заповніть його випадковими цілими числами від -5 до 5 та знайдіть суму модулів його елементів.

matrix = np.random.randint(-5, 6, size=(9, 9))
sum_of_abs_elements = np.sum(np.abs(matrix))
print("Масив:")
print(matrix)
print("Сума модулів елементів масиву:", sum_of_abs_elements)

Масив:
[[ 5 -5  1  5  3 -2  4  1  0]
 [ 3 -3 -1  4  5 -2 -4 -2  1]
 [ 1 -4 -5 -1 -1  4  1  3  5]
 [ 0 -1  4 -3  4  2  3  5  0]
 [ 0  0 -5 -5 -4  0 -5 -1  1]
 [ 0 -3 -5  2  1 -2  5  3  5]
 [ 2  0  5  3  4  2  1 -3 -4]
 [ 3  0  4  0  2  0 -3  0 -4]
 [ 0 -5 -5  0 -1  2 -4 -3 -2]]
Сума модулів елементів масиву: 207


In [7]:
#4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами 
#в діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

matrix = np.random.rand(3, 3)
geometric_mean = np.prod(matrix) ** (1 / matrix.size)
print("Масив:")
print(matrix)
print("Середнє геометричне всіх елементів масиву:", geometric_mean)

Масив:
[[0.82362322 0.89425465 0.33793673]
 [0.70425599 0.81974058 0.30407028]
 [0.37441571 0.2847165  0.53719687]]
Середнє геометричне всіх елементів масиву: 0.5139524289811875


In [8]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими дійсними 
#числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.rand(5)
b = np.random.rand(5)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [0.49110868 0.78487725 0.97900907 0.07634837 0.71525425]
b =  [0.00492592 0.8651543  0.59934414 0.57802705 0.43338799]
a + b =  [0.4960346  1.65003155 1.57835322 0.65437542 1.14864225]
a - b =  [ 0.48618277 -0.08027705  0.37966493 -0.50167868  0.28186626]
a * b =  [0.00241916 0.67903993 0.58676335 0.04413142 0.30998261]


In [9]:
#6.Створіть два вектори розміром 6, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.
a = np.random.rand(6)
b = np.random.rand(6)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [0.8553043  0.10615967 0.10580447 0.02369814 0.08611305 0.25849821]
b =  [0.18713222 0.88993856 0.57749041 0.69535509 0.73185331 0.79692727]
Скалярний добуток векторів дорівнює: 0.6011366634691317


In [10]:
#7.Створіть дві матриці розміром 2x3 та 3x2, заповніть 
#їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою.
a = np.random.randint(1, 16, size=(2, 3))
b = np.random.randint(1, 16, size=(3, 2))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[ 1  9  7]
 [ 6 11 14]]
b =  [[ 3 11]
 [ 7 10]
 [11  4]]
Результат множення матриць:
[[143 129]
 [249 232]]


In [11]:
#8.	Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.
a = np.random.randint(1, 16, size=(3, 3))
print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)

Вихідна матриця:
[[ 7 14  1]
 [15  7  6]
 [ 5  4 14]]
Обернена матриця:
[[-0.03743045  0.09711684 -0.0389479 ]
 [ 0.09104704 -0.04704097  0.01365706]
 [-0.01264542 -0.02124431  0.08143652]]


In [12]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 10 та транспонуйте її.
a = np.random.randint(0, 11, size=(4, 4))
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[ 5  0  4  5]
 [ 5  8 10  4]
 [ 8  8  8  7]
 [ 0  9  6  5]]
Транспонована матриця:
[[ 5  5  8  0]
 [ 0  8  8  9]
 [ 4 10  8  6]
 [ 5  4  7  5]]


In [24]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1,
#а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів отриманої матриці.
matrix = np.random.rand(3, 4)
vector = np.random.rand(4)
result = np.dot(matrix, vector)
sum_result = np.sum(result)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Результат перемноження:")
print(result)
print("Сума елементів отриманої матриці:", sum_result)


Матриця:
[[0.98924609 0.75352    0.82101236 0.94777441]
 [0.97129093 0.35242034 0.76007708 0.39254044]
 [0.68951204 0.25140091 0.77787415 0.52532808]]
Вектор:
[0.46127228 0.11132352 0.39934108 0.28462654]
Результат перемноження:
[1.137822   0.90251968 0.80619904]
Сума елементів отриманої матриці: 2.8465407211930125


In [13]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1,
#а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matr = np.random.rand(2, 3)
vect = np.random.rand(3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат добутку матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.86130209 0.61183812 0.3040605 ]
 [0.93041117 0.08053237 0.00265537]]
Вектор:
[0.28153637 0.24761464 0.19418172]
Результат добутку матриці на вектор:
[0.45303093 0.2824012 ]


In [14]:
#12.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))
diagonal_sum = np.trace(matrix2)
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)
print("Сума елементів діагоналі другої матриці:", diagonal_sum)


Перша матриця:
[[ 2  4  2]
 [ 3  7 10]
 [ 5 10 10]]
Друга матриця:
[[2 4 5]
 [7 7 3]
 [5 8 8]]
Сума елементів діагоналі другої матриці: 17


In [21]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від -10 до 10
#та знайдіть добуток їх елементів.
matrix1 = np.random.randint(-10, 11, (2, 2))
matrix2 = np.random.randint(-10, 11, (2, 2))
result = np.prod(matrix1) * np.prod(matrix2)

# Виведення матриць та добутку їх елементів
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)
print("Добуток елементів матриць:", result)


Перша матриця:
[[  6  -9]
 [-10   4]]
Друга матриця:
[[ 6 -1]
 [-5  7]]
Добуток елементів матриць: 453600


In [22]:
#14.Створіть матрицю розміром 10x10, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть найбільший елемент матриці.
matrix = np.random.randint(1, 101, (10, 10))

# Знаходження найбільшого елемента матриці
max_element = np.max(matrix)

# Виведення матриці та найбільшого елемента
print("Матриця:")
print(matrix)
print("Найбільший елемент матриці:", max_element)

Матриця:
[[18 21 73 85 39 60 52 50 94  2]
 [51 72 52 80 72 43  4 91 65 17]
 [ 8 63 66 80 65  5 81 11 53 13]
 [52 34 38 69 18 53 91 44 31 62]
 [47 37 34 21  5 34 52 87 48 23]
 [78 95 38 97 27 85 95 41 83 73]
 [75 61 87 37 12 73 39 48 47 20]
 [17  2 33 36 71 29 13 80 46 57]
 [21 88 27 24 81 77  9 73 52 35]
 [33 91 24  6 77 93 43 80  3 81]]
Найбільший елемент матриці: 97


In [23]:
#15.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та 
#знайдіть вектор-стовпчик,що містить кількість від'ємних елементів в кожному рядку матриці.

matrix = np.random.uniform(-1, 1, (4, 4))
vid = np.sum(matrix < 0, axis=1)
vid1 = vid.reshape(-1, 1)
print("Матриця:")
print(matrix)
print("Вектор-стовпчик з кількістю від'ємних елементів в кожному рядку:")
print(vid1)

Матриця:
[[ 0.83890999  0.88780297 -0.27855382  0.55198688]
 [ 0.69392218  0.26609017  0.47244562  0.39302584]
 [ 0.95905719  0.69147796  0.63173424 -0.24354672]
 [ 0.30496284 -0.92979908  0.4474545   0.49599972]]
Вектор-стовпчик з кількістю від'ємних елементів в кожному рядку:
[[1]
 [0]
 [1]
 [1]]
